import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Search, ShieldCheck, Wallet, Swords, CircleHelp } from 'lucide-react'
import { Button, ConfirmModal, EmptyState, FormField, Modal, PageTitle, Panel, Status } from './components'
import { deposits as seedDeposits, payouts as seedPayouts, users as seedUsers, games as seedGames, formatINR } from './data'
import { calculateMatchFinancials } from './finance'

export function AdminPage({section,notify}) {
  if(section==='summary') return <AdminSummary/>
  if(section==='deposits') return <Deposits notify={notify}/>
  if(section==='payouts') return <Payouts notify={notify}/>
  if(section==='settlements') return <Settlements notify={notify}/>
  if(section==='games') return <GamesAdmin notify={notify}/>
  if(section==='payments') return <PaymentsAdmin notify={notify}/>
  if(section==='users') return <UsersAdmin notify={notify}/>
  return <SupportAdmin notify={notify}/>
}

function AdminSummary() {
  const metrics=[['Total deposits','₹12,84,500',Wallet,'icon-indigo'],['Total withdrawals','₹4,28,000',Wallet,'icon-blue'],['Matches played','8,420',Swords,'icon-green'],['Platform earnings','₹1,42,800',ShieldCheck,'icon-amber'],['Pending deposits','₹18,500',Wallet,'icon-amber'],['Pending withdrawals','₹32,000',Wallet,'icon-blue'],['Pending disputes','12',CircleHelp,'icon-red']]
  return <><PageTitle eyebrow="ADMINISTRATION" title="Platform summary" subtitle="Monitor operations, payments, and player activity."/><div className="admin-kpi-grid">{metrics.map(([label,value,Icon,accent])=><article className="stat-card" key={label}><span className={`stat-icon ${accent}`}><Icon size={18}/></span><small>{label}</small><strong>{value}</strong><span className="stat-note">Updated just now</span></article>)}</div><div className="content-grid"><Panel title="Operations at a glance" subtitle="Today's platform activity"><div className="overview-bars">{[['Deposits received','₹84,500',78],['Withdrawals processed','₹32,000',41],['Matches completed','1,248',66],['Disputes resolved','28',34]].map(([label,value,width])=><div className="overview-bar" key={label}><span>{label}<strong>{value}</strong></span><i><b style={{width:`${width}%`}}/></i></div>)}</div></Panel><Panel title="Needs attention" subtitle="Items waiting for admin review"><div className="attention-list">{[['Deposits awaiting approval','8 requests','/admin/deposits'],['Payouts to process','5 requests','/admin/payouts'],['Match disputes','12 reports','/admin/settlements']].map(([label,detail,path])=><Link to={path} className="attention-item" key={label}><span><strong>{label}</strong><small>{detail}</small></span><b>→</b></Link>)}</div></Panel></div></>
}

function AdminTabs({items,value,onChange}) { return <div className="filter-tabs">{items.map(item=><button key={item} type="button" aria-pressed={value===item} className={value===item?'selected':''} onClick={()=>onChange(item)}>{item}</button>)}</div> }

function Deposits({notify}) {
  const [tab,setTab]=useState('Pending'); const [rows,setRows]=useState(seedDeposits); const [confirm,setConfirm]=useState(null); const [proof,setProof]=useState(null)
  const visible=rows.filter(row=>row.status===tab)
  function act(status){setRows(current=>current.map(row=>row.id===confirm.id?{...row,status}:row));notify(`Deposit ${confirm.id} ${status.toLowerCase()}`);setConfirm(null)}
  return <><PageTitle eyebrow="PAYMENT OPERATIONS" title="Deposits" subtitle="Review player payment proofs and confirm wallet credits."/><AdminTabs items={['Pending','Completed','Failed']} value={tab} onChange={setTab}/><Panel className="admin-table-deposits" title={`${tab} deposits`} subtitle={`${visible.length} requests in this queue`}><div className="table-wrap"><table><thead><tr><th>Request</th><th>Player</th><th>Amount</th><th>Method</th><th>Requested</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><strong>{row.id}</strong></td><td>{row.user}<small>{row.phone}</small></td><td><strong>{formatINR(row.amount)}</strong></td><td>{row.method}</td><td>{row.date}</td><td><Status>{row.status}</Status></td><td><div className="table-actions"><Button variant="ghost" onClick={()=>setProof(row)}>View proof</Button>{row.status==='Pending'&&<><Button variant="success" onClick={()=>setConfirm({row,status:'Completed'})}>Approve</Button><Button variant="danger-outline" onClick={()=>setConfirm({row,status:'Failed'})}>Reject</Button></>}</div></td></tr>)}</tbody></table></div>{visible.length===0&&<EmptyState title="Queue is clear" description="There are no deposit requests in this status."/>}</Panel>{confirm&&<ConfirmModal title={`${confirm.status} deposit?`} message={`${confirm.status==='Completed'?'Approve':'Reject'} the ${formatINR(confirm.row.amount)} deposit from ${confirm.row.user}? This is a mock action.`} confirmLabel={confirm.status} danger={confirm.status==='Failed'} onClose={()=>setConfirm(null)} onConfirm={()=>act(confirm.status)}/ >}{proof&&<Modal title={`Payment proof · ${proof.id}`} onClose={()=>setProof(null)}><div className="proof-preview"><span>UPI PAYMENT RECEIPT</span><strong>{formatINR(proof.amount)}</strong><small>Paid by {proof.user}</small><small>UPI transaction · 624108522930</small><span className="proof-placeholder">Payment screenshot preview</span></div><div className="modal-actions"><Button variant="secondary" onClick={()=>setProof(null)}>Close</Button></div></Modal>}</>
}

function Payouts({notify}) {
  const [rows,setRows]=useState(seedPayouts); const [confirm,setConfirm]=useState(null)
  return <><PageTitle eyebrow="PAYMENT OPERATIONS" title="Payouts" subtitle="Review withdrawal requests and keep payouts moving securely."/><Panel className="admin-table-payouts" title="Withdrawal requests" subtitle={`${rows.filter(row=>row.status==='Pending').length} requests need attention`}><div className="table-wrap"><table><thead><tr><th>User</th><th>Phone</th><th>Amount</th><th>UPI ID</th><th>Requested date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.user}</strong><small>{row.id}</small></td><td>{row.phone}</td><td><strong>{formatINR(row.amount)}</strong></td><td>{row.upi}</td><td>{row.date}</td><td><Status>{row.status}</Status></td><td><div className="table-actions">{(row.status==='Pending'||row.status==='Processing')&&<>{row.status==='Pending'&&<Button variant="secondary" onClick={()=>setConfirm({row,status:'Processing'})}>Process</Button>}<Button variant="success" onClick={()=>setConfirm({row,status:'Completed'})}>Approve</Button><Button variant="danger-outline" onClick={()=>setConfirm({row,status:'Rejected'})}>Reject</Button></>}</div></td></tr>)}</tbody></table></div></Panel>{confirm&&<ConfirmModal title={`${confirm.status} payout?`} message={`${confirm.status} ${formatINR(confirm.row.amount)} payout to ${confirm.row.user} (${confirm.row.upi})?`} confirmLabel={confirm.status} danger={confirm.status==='Rejected'} onClose={()=>setConfirm(null)} onConfirm={()=>{setRows(rows.map(row=>row.id===confirm.row.id?{...row,status:confirm.status}:row));notify(`Payout ${confirm.row.id} updated`);setConfirm(null)}}/>}</>
}

function Settlements({notify}) {
  const [decision,setDecision]=useState(null)
  const [screens,setScreens]=useState(null)
  const [rows,setRows]=useState([{id:'NX-2841',players:'Aarav Mehta vs Priya Sharma',entry:100,pool:calculateMatchFinancials(100,100).grossPool,claim:'Aarav Mehta',screens:2,status:'Disputed'},{id:'NX-2838',players:'Rohan Kapoor vs Ishita Rao',entry:50,pool:calculateMatchFinancials(50,50).grossPool,claim:'Ishita Rao',screens:1,status:'Under review'},{id:'NX-2810',players:'Kabir Singh vs Neha Verma',entry:500,pool:calculateMatchFinancials(500,500).grossPool,claim:'Kabir Singh',screens:2,status:'Disputed'}])
  return <><PageTitle eyebrow="MATCH OPERATIONS" title="Settlements" subtitle="Review winner claims, screenshots, and match disputes."/><Panel className="admin-table-settlements" title="Match settlements" subtitle="Review claims and update each match resolution"><div className="table-wrap"><table><thead><tr><th>Match</th><th>Players</th><th>Entry</th><th>Prize pool</th><th>Winner claim</th><th>Screenshots</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.id}</strong></td><td>{row.players}</td><td>{formatINR(row.entry)}</td><td>{formatINR(row.pool)}</td><td>{row.claim}</td><td><button className="text-link" onClick={()=>setScreens(row)}>View {row.screens} files</button></td><td><Status>{row.status}</Status></td><td><div className="table-actions">{['Disputed','Under review'].includes(row.status)&&<><Button variant="success" onClick={()=>setDecision({row,action:'Declare Winner'})}>Declare winner</Button><Button variant="secondary" onClick={()=>setDecision({row,action:'Refund Both'})}>Refund both</Button><Button variant="danger-outline" onClick={()=>setDecision({row,action:'Reject Claim'})}>Reject claim</Button></>}</div></td></tr>)}</tbody></table></div></Panel>{decision&&<ConfirmModal title={`${decision.action}?`} message={`${decision.action} for match ${decision.row.id} (${decision.row.players})? This will be recorded in the mock settlement log.`} confirmLabel={decision.action} danger={decision.action==='Reject Claim'} onClose={()=>setDecision(null)} onConfirm={()=>{const status=decision.action==='Declare Winner'?'Settled':decision.action==='Refund Both'?'Refunded':'Claim rejected';setRows(current=>current.map(row=>row.id===decision.row.id?{...row,status}:row));notify(`${decision.action} recorded for ${decision.row.id}`);setDecision(null)}}/>}{screens&&<Modal title={`Match screenshots · ${screens.id}`} onClose={()=>setScreens(null)}><div className="proof-preview"><span>PLAYER SUBMISSIONS</span><strong>{screens.screens} screenshots</strong><small>Winner claim by {screens.claim}</small><div className="screenshot-mock">Game result · Screenshot 01</div>{screens.screens>1&&<div className="screenshot-mock">Final board · Screenshot 02</div>}</div><div className="modal-actions"><Button variant="secondary" onClick={()=>setScreens(null)}>Close</Button></div></Modal>}</>
}

function GamesAdmin({notify}) {
  const [rows,setRows]=useState(seedGames.map(game=>({...game,active:true}))); const [editing,setEditing]=useState(null)
  function saveGame(event){event.preventDefault();const form=new FormData(event.currentTarget);const data={name:form.get('name'),category:form.get('category'),entry:Number(form.get('entry'))};if(editing==='new'){setRows([...rows,{id:`game-${Date.now()}`,...data,players:0,symbol:'🎮',theme:'carrom',active:true}]);notify('Game added to the catalog')}else{setRows(rows.map(item=>item.id===editing.id?{...item,...data}:item));notify(`${data.name} updated`)}setEditing(null)}
  return <><PageTitle eyebrow="CATALOG MANAGEMENT" title="Games" subtitle="Manage the games available to players." action={<Button onClick={()=>setEditing('new')}><Plus size={16}/> Add game</Button>}/><Panel title="Game catalog" subtitle="Edit listing details or switch game availability."><div className="admin-game-list">{rows.map(game=><article className="admin-game-row" key={game.id}><div className={`game-mini ${game.theme}`}>{game.symbol}</div><div className="row-grow"><strong>{game.name}</strong><small>{game.category} · Entry from {formatINR(game.entry)} · {game.players.toLocaleString('en-IN')} players</small></div><Status>{game.active?'Active':'Inactive'}</Status><Button variant="ghost" onClick={()=>setEditing(game)}>Edit</Button><button className={`toggle ${game.active?'on':''}`} aria-label={`${game.active?'Disable':'Enable'} ${game.name}`} onClick={()=>{setRows(rows.map(item=>item.id===game.id?{...item,active:!item.active}:item));notify(`${game.name} availability updated`)}}/></article>)}</div></Panel>{editing&&<Modal title={editing==='new'?'Add a game':`Edit ${editing.name}`} onClose={()=>setEditing(null)}><form className="form-stack" onSubmit={saveGame}><FormField label="Game name"><input name="name" required defaultValue={editing==='new'?'':editing.name} placeholder="e.g. Table Tennis"/></FormField><FormField label="Category"><select name="category" defaultValue={editing==='new'?'Strategy':editing.category}><option>Strategy</option><option>Board game</option><option>Sports</option><option>Classic</option></select></FormField><FormField label="Entry fee"><select name="entry" defaultValue={editing==='new'?50:editing.entry}><option value="50">₹50</option><option value="100">₹100</option><option value="500">₹500</option><option value="1000">₹1,000</option></select></FormField><div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit">{editing==='new'?'Add game':'Save changes'}</Button></div></form></Modal>}</>
}

function PaymentsAdmin({notify}) {
  const [active,setActive]=useState('PM-001'); const [modal,setModal]=useState(false); const [methods,setMethods]=useState([{id:'PM-001',upi:'playnexa@okaxis',payee:'Play Nexa Technologies',bank:'Axis Bank · Current account',qr:'Primary collection QR'},{id:'PM-002',upi:'payments@okicici',payee:'Play Nexa Technologies',bank:'ICICI Bank · Current account',qr:'Backup collection QR'}])
  function addMethod(event){event.preventDefault();const form=new FormData(event.currentTarget);const file=form.get('qr');setMethods([...methods,{id:`PM-${Date.now()}`,upi:form.get('upi'),payee:form.get('payee'),bank:'Custom bank account',qr:file?.name||'QR image uploaded'}]);setModal(false);notify('Payment method saved as inactive. Existing active method retained.')}
  return <><PageTitle eyebrow="PAYMENT CONFIGURATION" title="Payment methods" subtitle="Configure collection accounts and QR codes. Only one method can be active." action={<Button onClick={()=>setModal(true)}><Plus size={16}/> Add payment method</Button>}/><div className="info-banner"><ShieldCheck size={18}/><span>Exactly one payment method should remain active so deposits are routed consistently.</span></div><div className="payment-method-grid">{methods.map(method=><article className={`payment-method ${active===method.id?'method-active':''}`} key={method.id}><div className="payment-method-head"><span className="upi-mark">UPI</span><Status>{active===method.id?'Active':'Inactive'}</Status></div><small>COLLECTION UPI ID</small><strong className="upi-value">{method.upi}</strong><p>{method.payee}</p><div className="qr-box"><span className="qr-mock">▦</span><span><strong>{method.qr}</strong><small>Linked to {method.bank}</small></span></div><Button variant={active===method.id?'secondary':'primary'} disabled={active===method.id} onClick={()=>{setActive(method.id);notify(`${method.upi} is now the only active payment method`)}}>{active===method.id?'Currently active':'Make active'}</Button></article>)}</div>{modal&&<Modal title="Add payment method" onClose={()=>setModal(false)}><form className="form-stack" onSubmit={addMethod}><FormField label="UPI ID"><input name="upi" placeholder="payments@bank" required/></FormField><FormField label="Payee name"><input name="payee" placeholder="Registered business name" required/></FormField><FormField label="QR image"><input name="qr" type="file" accept="image/*"/></FormField><div className="form-disclaimer">New methods are added inactive to protect the single active payment route.</div><div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setModal(false)}>Cancel</Button><Button type="submit">Save method</Button></div></form></Modal>}</>
}

function UsersAdmin({notify}) {
  const [rows,setRows]=useState(seedUsers); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All users')
  const visible=rows.filter(user=>`${user.name} ${user.phone} ${user.id}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All users'||user.status===filter.replace(' users','')))
  function update(user,action){setRows(rows.map(row=>row.id===user.id?{...row,...(action==='Block'?{status:'Blocked'}:action==='Unblock'||action==='Activate'?{status:'Active'}:action==='Deactivate'?{status:'Inactive'}:action==='Promote'?{role:'Moderator'}:{role:'Player'})}:row));notify(`${user.name}: ${action.toLowerCase()} action applied`)}
  return <><PageTitle eyebrow="PLAYER MANAGEMENT" title="Users" subtitle="Search player accounts and manage access or roles."/><div className="toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search players" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by name, phone, or ID"/></label><AdminTabs items={['All users','Active users','Blocked users']} value={filter} onChange={setFilter}/></div><Panel className="admin-table-users" title="Player accounts" subtitle={`${visible.length} accounts shown`}><div className="table-wrap"><table><thead><tr><th>User</th><th>Phone</th><th>Joined</th><th>Matches</th><th>Balance</th><th>Status / role</th><th>Actions</th></tr></thead><tbody>{visible.map(user=><tr key={user.id}><td><strong>{user.name}</strong><small>{user.id}</small></td><td>{user.phone}</td><td>{user.joined}</td><td>{user.matches}</td><td>{formatINR(user.balance)}</td><td><Status>{user.status}</Status><small>{user.role}</small></td><td><select className="action-select" value="" aria-label={`Actions for ${user.name}`} onChange={event=>event.target.value&&update(user,event.target.value)}><option value="" disabled>Choose action</option>{user.status==='Blocked'?<option>Unblock</option>:<><option>Activate</option><option>Deactivate</option><option>Block</option></>}{user.role==='Player'?<option>Promote</option>:<option>Demote</option>}</select></td></tr>)}</tbody></table></div>{!visible.length&&<EmptyState title="No matching players" description="Try another name, phone number, or account ID."/>}</Panel></>
}

function SupportAdmin({notify}) {
  const [tab,setTab]=useState('Open'); const [rows,setRows]=useState([{id:'TK-4038',user:'Aarav Mehta',topic:'Result not updated',date:'Oct 02, 10:32 AM',status:'Open'},{id:'TK-4022',user:'Diya Shah',topic:'Deposit not credited',date:'Oct 02, 9:18 AM',status:'In Progress'},{id:'TK-3991',user:'Rohan Kapoor',topic:'Withdrawal status',date:'Oct 01, 4:10 PM',status:'Open'},{id:'TK-3844',user:'Meera Nair',topic:'Update UPI ID',date:'Sep 25, 2:06 PM',status:'Resolved'}])
  const visible=rows.filter(row=>row.status===tab)
  return <><PageTitle eyebrow="PLAYER CARE" title="Support tickets" subtitle="Assign, update, and resolve player requests."/><AdminTabs items={['Open','In Progress','Resolved','Closed']} value={tab} onChange={setTab}/><Panel className="admin-table-support" title={`${tab} tickets`} subtitle={`${visible.length} tickets in this queue`}><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Player</th><th>Topic</th><th>Created</th><th>Status</th><th>Update status</th></tr></thead><tbody>{visible.map(ticket=><tr key={ticket.id}><td><strong>{ticket.id}</strong></td><td>{ticket.user}</td><td>{ticket.topic}</td><td>{ticket.date}</td><td><Status>{ticket.status}</Status></td><td><select className="action-select" value={ticket.status} onChange={event=>{setRows(rows.map(row=>row.id===ticket.id?{...row,status:event.target.value}:row));notify(`Ticket ${ticket.id} moved to ${event.target.value}`)}}>{['Open','In Progress','Resolved','Closed'].map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>{!visible.length&&<EmptyState title="Queue is clear" description="There are no support tickets in this status."/>}</Panel></>
}
