import { useState } from 'react'
import { BrowserRouter, NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { Activity, ArrowDownLeft, ArrowLeftRight, ArrowUpRight, Bell, ChevronDown, CircleHelp, Gamepad2, Headphones, LayoutDashboard, Menu, Search, Settings, ShieldCheck, Swords, Trophy, Users, Wallet, X, Zap } from 'lucide-react'
import './App.css'

const nav = [
  { label: 'Overview', to: '/', icon: LayoutDashboard }, { label: 'Play games', to: '/games', icon: Gamepad2 },
  { label: 'My matches', to: '/matches', icon: Swords }, { label: 'Wallet', to: '/wallet', icon: Wallet },
  { label: 'Support', to: '/support', icon: CircleHelp },
]
const games = [
  { name: 'Chess', category: 'Strategy', players: '1.2k playing', icon: '♟', color: 'chess', prize: 'Up to ₹2,000' },
  { name: 'Ludo', category: 'Board game', players: '856 playing', icon: '🎲', color: 'ludo', prize: 'Up to ₹1,000' },
  { name: '8 Ball Pool', category: 'Sports', players: '642 playing', icon: '🎱', color: 'pool', prize: 'Up to ₹1,500' },
]
const transactions = [
  { title: 'Match won · Chess', date: 'Today, 10:42 AM', amount: '+₹240', positive: true, icon: Trophy },
  { title: 'Entry fee · Ludo', date: 'Today, 9:18 AM', amount: '−₹50', positive: false, icon: ArrowUpRight },
  { title: 'Wallet top-up', date: 'Yesterday, 5:06 PM', amount: '+₹500', positive: true, icon: ArrowDownLeft },
]

function Sidebar({ close }) {
  return <aside className="sidebar">
    <NavLink to="/" className="brand" onClick={close}><span className="brand-mark"><Zap size={20} fill="currentColor" /></span><span>play<span className="brand-accent">nexa</span></span></NavLink>
    <div className="side-label">MENU</div>
    <nav className="side-nav">{nav.map(({ label, to, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={close} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={18} strokeWidth={1.8} /><span>{label}</span>{label === 'My matches' && <span className="nav-count">2</span>}</NavLink>)}</nav>
    <div className="side-label admin-label">MANAGE</div>
    <nav className="side-nav"><NavLink to="/admin" onClick={close} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><ShieldCheck size={18} /><span>Admin dashboard</span></NavLink></nav>
    <div className="sidebar-bottom"><div className="help-box"><div className="help-icon"><Headphones size={18} /></div><strong>Need a hand?</strong><p>Our team is here to help.</p><NavLink to="/support" onClick={close}>Contact support <span>↗</span></NavLink></div><NavLink to="/login" className="user-profile"><span className="avatar">AR</span><span className="profile-copy"><strong>Alex Rivera</strong><small>Player account · Sign out</small></span><ChevronDown size={16} /></NavLink></div>
  </aside>
}

function Header({ title, onMenu }) {
  return <header className="topbar"><button className="mobile-menu icon-button" onClick={onMenu} aria-label="Open menu"><Menu size={20} /></button><div className="crumb"><span>Play Nexa</span><span className="crumb-slash">/</span><strong>{title}</strong></div><div className="top-actions"><label className="searchbox"><Search size={16} /><input placeholder="Search anything..." /></label><button className="icon-button notification" aria-label="Notifications"><Bell size={18} /><i /></button><span className="top-avatar">AR</span></div></header>
}

function PageHeading({ eyebrow, title, subtitle, action }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</div> }
function StatCard({ label, value, delta, icon: Icon, tone }) { return <article className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><span className="stat-label">{label}</span><strong className="stat-value">{value}</strong><div className="stat-foot"><span className="delta">↗ {delta}</span><span>vs last week</span></div></article> }
function GameCard({ game }) { return <article className="game-card"><div className={`game-cover ${game.color}`}><span className="game-symbol">{game.icon}</span><span className="live-pill"><i /> LIVE</span></div><div className="game-info"><div className="game-category">{game.category}</div><h3>{game.name}</h3><div className="game-meta"><span><Users size={14} /> {game.players}</span><b>{game.prize}</b></div><NavLink className="button button-primary game-cta" to={`/lobby/${encodeURIComponent(game.name.toLowerCase().replaceAll(' ', '-'))}`}>Play now <span>→</span></NavLink></div></article> }
function ActivityList() { return <div className="activity-list">{transactions.map(({ title, date, amount, positive, icon: Icon }) => <div className="activity-row" key={title}><div className={`activity-icon ${positive ? 'green' : ''}`}><Icon size={16} /></div><div className="activity-copy"><strong>{title}</strong><span>{date}</span></div><b className={positive ? 'amount-positive' : ''}>{amount}</b></div>)}</div> }

function Dashboard() {
  return <><PageHeading eyebrow="THURSDAY, OCTOBER 2, 2026" title={<>Good afternoon, Alex <span className="wave">✌️</span></>} subtitle="Ready to put your skills to the test?" action={<NavLink className="button button-primary" to="/games"><Gamepad2 size={17} /> Find a match</NavLink>} />
    <section className="stats-grid"><StatCard label="Wallet balance" value="₹2,450.00" delta="12.5%" icon={Wallet} tone="violet" /><StatCard label="Matches played" value="128" delta="8.2%" icon={Swords} tone="blue" /><StatCard label="Total winnings" value="₹8,640" delta="18.4%" icon={Trophy} tone="amber" /><StatCard label="Win rate" value="68.4%" delta="4.6%" icon={Activity} tone="green" /></section>
    <section className="dashboard-grid"><div className="section-card games-section"><div className="section-heading"><div><h2>Popular games</h2><p>Jump into a game and challenge players</p></div><NavLink to="/games" className="text-link">View all <span>→</span></NavLink></div><div className="games-grid">{games.map(game => <GameCard key={game.name} game={game} />)}</div></div>
      <aside className="section-card activity-section"><div className="section-heading"><div><h2>Recent activity</h2><p>Your latest transactions</p></div><NavLink to="/wallet" className="text-link">See all <span>→</span></NavLink></div><ActivityList /><NavLink to="/wallet" className="activity-footer"><ArrowLeftRight size={15} /> View transaction history <span>→</span></NavLink></aside></section>
    <section className="challenge-banner"><div className="challenge-art"><span className="challenge-orb orb-one" /><span className="challenge-orb orb-two" /><Trophy size={44} /></div><div className="challenge-copy"><span className="challenge-tag"><i /> WEEKLY CHALLENGE</span><h2>Ready for the weekend showdown?</h2><p>Join this week's tournament and compete for a share of <strong>₹25,000</strong>.</p></div><NavLink className="button button-white" to="/games">Explore tournaments <span>→</span></NavLink></section>
  </>
}

const pageContent = {
  '/games': { title: 'Find your next game', subtitle: 'Choose a game, set your stakes, and show them what you’ve got.' },
  '/matches': { title: 'My matches', subtitle: 'Track your active games and revisit past results.' },
  '/wallet': { title: 'Your wallet', subtitle: 'Manage your balance and keep track of every rupee.' },
  '/support': { title: 'How can we help?', subtitle: 'Find answers or get in touch with our support team.' },
  '/admin': { title: 'Admin overview', subtitle: 'Platform activity and operations at a glance.' },
}
function GenericPage({ path }) {
  const content = pageContent[path]
  if (path === '/games') return <><PageHeading eyebrow="GAME LOBBY" title={content.title} subtitle={content.subtitle} /><div className="filter-row"><button className="filter-chip selected">All games</button><button className="filter-chip">Strategy</button><button className="filter-chip">Board games</button><button className="filter-chip">Sports</button><span className="online-count"><i /> 2,714 players online</span></div><div className="games-grid games-page-grid">{games.map(game => <GameCard key={game.name} game={game} />)}</div><div className="section-card empty-callout"><div className="empty-symbol">✦</div><div><strong>More games are on the way</strong><p>We’re always adding new ways to play. Check back soon!</p></div></div></>
  if (path === '/matches') return <><PageHeading eyebrow="YOUR GAME HISTORY" title={content.title} subtitle={content.subtitle} /><div className="filter-row"><button className="filter-chip selected">All matches</button><button className="filter-chip">Active</button><button className="filter-chip">Completed</button></div><div className="section-card table-card"><div className="table-head"><span>GAME</span><span>OPPONENT</span><span>DATE</span><span>ENTRY</span><span>RESULT</span></div>{[{game:'Chess',icon:'♟',op:'Jordan Lee',date:'Today, 10:42 AM',fee:'₹50',result:'Won · +₹240',win:true},{game:'Ludo',icon:'🎲',op:'Sam Taylor',date:'Today, 9:18 AM',fee:'₹50',result:'In progress',active:true},{game:'8 Ball Pool',icon:'🎱',op:'Casey Morgan',date:'Yesterday, 4:30 PM',fee:'₹100',result:'Lost · −₹100'}].map(row=><div className="table-row" key={row.game}><div className="table-game"><span>{row.icon}</span><b>{row.game}</b></div><span>{row.op}</span><span>{row.date}</span><span>{row.fee}</span><span className={row.win?'amount-positive':row.active?'status-active':'status-lost'}>{row.result}</span></div>)}</div></>
  if (path === '/wallet') return <><PageHeading eyebrow="PAYMENTS & ACTIVITY" title={content.title} subtitle={content.subtitle} action={<button className="button button-primary"><ArrowDownLeft size={17} /> Add money</button>} /><div className="wallet-balance"><span>AVAILABLE BALANCE</span><strong>₹2,450<span>.00</span></strong><small><i /> Wallet active and ready to play</small></div><div className="section-card wallet-transactions"><div className="section-heading"><div><h2>Recent transactions</h2><p>Your wallet activity at a glance</p></div><button className="filter-chip">All activity <ChevronDown size={14}/></button></div><ActivityList /></div></>
  if (path === '/support') return <><PageHeading eyebrow="PLAYER CARE" title={content.title} subtitle={content.subtitle} /><div className="support-grid">{[{icon:CircleHelp,title:'Help center',text:'Browse quick answers to common questions.',link:'Browse articles'},{icon:Headphones,title:'Talk to our team',text:'We typically reply in a few minutes.',link:'Start a conversation'},{icon:Settings,title:'Account & safety',text:'Keep your account secure and up to date.',link:'Manage account'}].map(({icon:Icon,title,text,link})=><article className="section-card support-card" key={title}><div className="stat-icon violet"><Icon size={20}/></div><h2>{title}</h2><p>{text}</p><button className="text-link">{link} <span>→</span></button></article>)}</div><div className="section-card faq-card"><h2>Frequently asked questions</h2>{['How do I withdraw my winnings?','When will my match winnings arrive?','How do I report a player?'].map(x=><button key={x}>{x}<span>＋</span></button>)}</div></>
  return <><PageHeading eyebrow="PLATFORM OPERATIONS" title={content.title} subtitle={content.subtitle} /><section className="stats-grid"><StatCard label="Active players" value="12,840" delta="6.8%" icon={Users} tone="violet"/><StatCard label="Matches today" value="3,216" delta="11.2%" icon={Swords} tone="blue"/><StatCard label="Platform volume" value="₹4.82L" delta="14.1%" icon={Wallet} tone="amber"/><StatCard label="Open reports" value="18" delta="3 resolved" icon={ShieldCheck} tone="green"/></section><div className="section-card admin-note"><div className="stat-icon blue"><Activity size={20}/></div><div><h2>Platform is running smoothly</h2><p>All services operational · Last updated just now</p></div><span className="online-count"><i/> All systems normal</span></div><section className="dashboard-grid admin-tables"><div className="section-card"><div className="section-heading"><div><h2>Latest reports</h2><p>Player reports awaiting review</p></div><button className="text-link">View queue →</button></div><div className="activity-list"><div className="activity-row"><div className="activity-icon"><ShieldCheck size={16}/></div><div className="activity-copy"><strong>Unsportsmanlike conduct</strong><span>Reported 8 min ago · Match #NX-2841</span></div><span className="priority-pill">Review</span></div><div className="activity-row"><div className="activity-icon"><ShieldCheck size={16}/></div><div className="activity-copy"><strong>Suspected account sharing</strong><span>Reported 24 min ago · Player #PL-0920</span></div><span className="priority-pill">Review</span></div></div></div><div className="section-card"><div className="section-heading"><div><h2>Quick actions</h2><p>Common admin tasks</p></div></div><div className="quick-actions"><button><Users size={16}/> Manage players <span>→</span></button><button><Swords size={16}/> Match disputes <span>→</span></button><button><Wallet size={16}/> Payment reviews <span>→</span></button></div></div></section></>
}

function Lobby() {
  const { game } = useParams(); const gameName = games.find(item => item.name.toLowerCase().replaceAll(' ', '-') === game)?.name || 'Chess'
  return <><PageHeading eyebrow="MATCHMAKING" title="Find an opponent" subtitle={`You’re entering the ${gameName} lobby. Choose an entry fee to find a fair match.`} /><div className="section-card lobby-card"><div className="lobby-game">{games.find(item => item.name === gameName)?.icon || '♟'}</div><div className="lobby-copy"><span className="eyebrow">QUICK MATCH</span><h2>{gameName}</h2><p>Players online now <b>· 1,248</b></p></div><span className="online-count"><i/> Matchmaking online</span></div><h2 className="subheading">Choose your entry fee</h2><div className="stake-grid">{[{fee:'₹25',prize:'Win ₹45'},{fee:'₹50',prize:'Win ₹90'},{fee:'₹100',prize:'Win ₹180'}].map((item,index)=><NavLink to="/match/NX-2841" className={`stake-card ${index===1?'stake-selected':''}`} key={item.fee}><span className="stake-label">ENTRY FEE</span><strong>{item.fee}</strong><span>{item.prize}</span>{index===1&&<i>POPULAR</i>}</NavLink>)}</div><div className="section-card matchmaking-note"><div className="stat-icon violet"><Users size={18}/></div><div><strong>Fair and balanced matches</strong><p>We’ll pair you with someone close to your skill level.</p></div></div></>
}
function MatchDetails() { return <><PageHeading eyebrow="MATCH #NX-2841" title="Match ready" subtitle="Your opponent is waiting. Good luck, play fair!" /><div className="section-card match-card"><span className="match-status"><i/> READY TO PLAY</span><div className="match-players"><div><span className="match-avatar self">AR</span><strong>Alex Rivera</strong><small>You · 1,240 rating</small></div><b className="versus">VS</b><div><span className="match-avatar opponent">JL</span><strong>Jordan Lee</strong><small>Opponent · 1,210 rating</small></div></div><div className="match-summary"><span><Gamepad2 size={15}/> Chess</span><span><Wallet size={15}/> Entry ₹50</span><span><Trophy size={15}/> Prize ₹90</span></div><NavLink to="/matches" className="button button-primary">Open game <span>→</span></NavLink></div><div className="match-detail-foot"><ShieldCheck size={15}/> Match results are determined by game performance and confirmed by both players.</div></> }
function Login() { return <div className="auth-screen"><NavLink to="/" className="brand"><span className="brand-mark"><Zap size={20} fill="currentColor"/></span><span>play<span className="brand-accent">nexa</span></span></NavLink><form className="auth-card" onSubmit={event=>{event.preventDefault();window.location.href='/'}}><span className="eyebrow">WELCOME BACK</span><h1>Sign in to Play Nexa</h1><p>Pick up where you left off and get back in the game.</p><label>Email address<input type="email" defaultValue="alex@example.com" required/></label><label>Password<input type="password" defaultValue="playnexa" required/></label><button className="button button-primary">Sign in <span>→</span></button><div className="auth-disclaimer">Demo account · Mock authentication only</div><div className="auth-bottom">New to Play Nexa? <button type="button">Create an account</button></div></form><small className="auth-legal">By continuing, you agree to our Terms of Service and Privacy Policy.</small></div> }
function Shell() {
  const location = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const isHome = location.pathname === '/'; const title = isHome ? 'Overview' : (pageContent[location.pathname]?.title || 'Overview')
  if(location.pathname==='/login') return <Login/>;
  return <div className="app-shell"><div className={`mobile-scrim ${menuOpen?'visible':''}`} onClick={()=>setMenuOpen(false)} /><div className={`sidebar-wrap ${menuOpen?'open':''}`}><Sidebar close={()=>setMenuOpen(false)} /><button className="mobile-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={18}/></button></div><main className="main-area"><Header title={title} onMenu={()=>setMenuOpen(true)} /><div className="page-content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/games" element={<GenericPage path="/games"/>}/><Route path="/lobby/:game" element={<Lobby/>}/><Route path="/match/:id" element={<MatchDetails/>}/><Route path="/matches" element={<GenericPage path="/matches"/>}/><Route path="/wallet" element={<GenericPage path="/wallet"/>}/><Route path="/support" element={<GenericPage path="/support"/>}/><Route path="/admin" element={<GenericPage path="/admin"/>}/><Route path="*" element={<Dashboard/>}/></Routes><footer className="footer"><span>© 2026 Play Nexa</span><span>Play fair. Play smart. <span className="footer-heart">♥</span></span><a href="mailto:support@playnexa.example">Need help?</a></footer></div></main></div>
}
export default function App() { return <BrowserRouter><Shell/></BrowserRouter> }
