import { useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowDownLeft, ArrowUpRight, Gamepad2, Headphones, Plus, ShieldCheck, Swords, Trophy, Upload, Wallet as WalletIcon } from 'lucide-react'
import { Button, ConfirmModal, CopyButton, DataState, EmptyState, FormField, Modal, PageTitle, Panel, Status } from './components'
import { formatINR, games, lobbyMatches, matches, player, tickets, transactions } from './data'
import { calculateMatchFinancials } from './finance'

function Stat({ icon: Icon, label, value, note, accent = '' }) {
  return <article className="stat-card"><span className={`stat-icon ${accent}`}><Icon size={18}/></span><small>{label}</small><strong>{value}</strong>{note && <span className="stat-note">{note}</span>}</article>
}

export function Dashboard() {
  return <><PageTitle eyebrow="THURSDAY, OCTOBER 2, 2026" title="Good afternoon, Aarav" subtitle="Your next great match is just around the corner." action={<Link to="/games" className="btn btn-primary"><Gamepad2 size={17}/> Find a match</Link>}/>
    <div className="stats-grid"><Stat icon={WalletIcon} accent="icon-indigo" label="Wallet balance" value={formatINR(player.balance)} note="Ready to play"/><Stat icon={Trophy} accent="icon-green" label="Today's earnings" value="₹1,240" note="↑ 18% from yesterday"/><Stat icon={Swords} accent="icon-amber" label="Matches played" value="48" note="32 wins · 67% win rate"/><Stat icon={ShieldCheck} accent="icon-blue" label="Skill rating" value="1,240" note="Gold league"/></div>
    <div className="content-grid"><Panel title="Popular games" subtitle="Find your next challenge" action={<Link className="text-link" to="/games">All games →</Link>}><div className="game-grid">{games.slice(0,3).map(game=><GameTile key={game.id} game={game}/>)}</div></Panel><Panel title="Active matches" subtitle="Pick up where you left off"><div className="compact-list">{matches.filter(match=>match.status!=='Completed').map(match=><div className="compact-row" key={match.id}><span className={`game-mini ${match.game.toLowerCase().replaceAll(' ','-')}`}>{games.find(game=>game.name===match.game)?.symbol}</span><div className="row-grow"><strong>{match.game} vs {match.opponent}</strong><small>{match.id} · Entry {formatINR(match.entry)}</small></div><Link className="text-link" to={`/match/${match.id}`}>Open →</Link></div>)}</div></Panel></div>
    <Panel title="Recent transactions" subtitle="Your latest wallet activity" action={<Link className="text-link" to="/wallet">View wallet →</Link>}><TransactionRows rows={transactions.slice(0,3)}/></Panel>
  </>
}

function GameTile({ game }) {
  return <article className="game-tile"><div className={`game-art ${game.theme}`}><span>{game.symbol}</span><small>{game.category}</small></div><div className="game-tile-info"><div><h3>{game.name}</h3><p>{game.players.toLocaleString('en-IN')} players online</p></div><div><small>Entry from</small><strong>{formatINR(game.entry)}</strong></div></div><Link className="btn btn-secondary game-play" to={`/games/${game.id}`}>Play <span>→</span></Link></article>
}

export function GamesPage() {
  const [filter, setFilter] = useState('All games')
  const categories = ['All games', 'Strategy', 'Board game', 'Sports', 'Classic']
  const visible = filter === 'All games' ? games : games.filter(game=>game.category===filter)
  return <><PageTitle eyebrow="GAME LOBBY" title="Choose your game" subtitle="Play for fun, compete for prizes, and keep it friendly."/><div className="filter-tabs">{categories.map(category=><button key={category} type="button" aria-pressed={filter===category} className={filter===category?'selected':''} onClick={()=>setFilter(category)}>{category}</button>)}</div><DataState loading={false} error={false} empty={!visible.length}><div className="game-grid game-grid-page">{visible.map(game=><GameTile key={game.id} game={game}/>)}</div></DataState></>
}

export function Lobby({ notify }) {
  const { game: gameId } = useParams(); const game=games.find(item=>item.id===gameId)||games[0]; const [modal,setModal]=useState(false); const [confirm,setConfirm]=useState(null); const [openMatches,setOpenMatches]=useState(()=>lobbyMatches.filter(match=>match.game===game.name)); const navigate=useNavigate()
  function createMatch(entry){const financials=calculateMatchFinancials(entry,entry);const idBase={chess:2900,ludo:3000,pool:3100,carrom:3200}[game.id];setOpenMatches([{id:`NX-${idBase+openMatches.length}`,game:game.name,creator:player.name,entry,pool:financials.grossPool,status:'Open'},...openMatches]);setModal(false);notify('Your match is open in the lobby')}
  return <><PageTitle eyebrow="OPEN MATCHES" title={`${game.name} lobby`} subtitle="Find a player and get into the game." action={<Button onClick={()=>setModal(true)}><Plus size={16}/> Create match</Button>}/><div className="lobby-hero"><div className={`lobby-badge ${game.theme}`}>{game.symbol}</div><div className="lobby-hero-copy"><h2>{game.name}</h2><p>{game.players.toLocaleString('en-IN')} players online · Entry from {formatINR(game.entry)}</p></div><Status>Open</Status></div><Panel className="admin-table-lobby" title="Open matches" subtitle="Join a player waiting for an opponent">{openMatches.length?<div className="table-wrap"><table><thead><tr><th>Match</th><th>Creator</th><th>Entry fee</th><th>Prize pool</th><th>Status</th><th/></tr></thead><tbody>{openMatches.map(match=><tr key={match.id}><td><strong>{match.id}</strong><small>{match.game}</small></td><td>{match.creator}</td><td>{formatINR(match.entry)}</td><td className="positive-text">{formatINR(match.pool)}</td><td><Status>{match.status}</Status></td><td><Button variant="secondary" onClick={()=>setConfirm(match)}>Join</Button></td></tr>)}</tbody></table></div>:<EmptyState title="No open matches" description="Create a match and invite a player to join." action={<Button onClick={()=>setModal(true)}><Plus size={15}/> Create match</Button>}/>}</Panel>{modal&&<CreateMatchModal game={game} onClose={()=>setModal(false)} onCreate={createMatch}/>}{confirm&&<ConfirmModal title="Join this match?" message={`${formatINR(confirm.entry)} will be reserved from your wallet. The prize pool is ${formatINR(confirm.pool)}.`} confirmLabel="Join match" onClose={()=>setConfirm(null)} onConfirm={()=>{setConfirm(null);notify('Match joined. Room details are ready.');navigate(`/match/${confirm.id}`,{state:{match:{...confirm,opponent:confirm.creator,room:`RM-${confirm.id.slice(-4)}`}}})}}/>}</>
}

function CreateMatchModal({game,onClose,onCreate}) {
  const [entry,setEntry]=useState(100)
  const financials=calculateMatchFinancials(entry,entry)
  return <Modal title="Create a match" onClose={onClose}><p className="modal-intro">Set up a {game.name} match and wait for an opponent.</p><form className="form-stack" onSubmit={event=>{event.preventDefault();onCreate(entry)}}><FormField label="Entry fee"><select value={entry} onChange={event=>setEntry(Number(event.target.value))}><option value="50">₹50</option><option value="100">₹100</option><option value="500">₹500</option><option value="1000">₹1,000</option></select></FormField><FormField label="Match note (optional)"><input placeholder="Add a note for your opponent" maxLength="80"/></FormField><div className="fee-summary"><span>Prize pool · winner receives</span><strong>{formatINR(financials.grossPool)} · {formatINR(financials.winnerAmount)}</strong></div><div className="modal-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Create match</Button></div></form></Modal>
}

export function MatchPage({notify}) {
  const {id}=useParams(); const location=useLocation(); const match=location.state?.match||matches.find(item=>item.id===id)||matches[0]; const financials=calculateMatchFinancials(match.entry,match.entry); const [confirm,setConfirm]=useState('')
  return <><PageTitle eyebrow={`MATCH ${match.id}`} title={`${match.game} match`} subtitle="Room details and match controls."/><Panel className="match-panel" title="Match details" subtitle="Share the room code with your opponent"><div className="match-versus"><div className="match-player"><span className="player-avatar">AM</span><strong>Aarav Mehta</strong><small>You · 1,240 rating</small></div><span className="versus">VS</span><div className="match-player"><span className="player-avatar opponent">PS</span><strong>{match.opponent}</strong><small>Opponent · 1,198 rating</small></div></div><div className="financial-grid"><div><small>Entry amount</small><strong>{formatINR(match.entry)} each</strong></div><div><small>Prize pool</small><strong>{formatINR(financials.grossPool)}</strong></div><div><small>Platform fee</small><strong>{formatINR(financials.platformFee)}</strong></div><div><small>Winner amount</small><strong className="positive-text">{formatINR(financials.winnerAmount)}</strong></div></div><div className="room-code"><div><small>ROOM CODE</small><strong>{match.room}</strong></div><CopyButton value={match.room} onCopied={()=>notify('Room code copied')}/></div></Panel><div className="content-grid match-actions"><Panel title="Submit match proof" subtitle="Upload a screenshot from the completed game"><label className="upload-box"><Upload size={20}/><strong>Choose a screenshot</strong><small>PNG or JPG · Max 10 MB</small><input type="file" accept="image/png,image/jpeg" onChange={event=>event.target.files?.length&&notify('Screenshot attached for review')}/></label><div className="button-row"><Button onClick={()=>setConfirm('Claim victory? Your screenshot will be reviewed before winnings are released.')}>Claim victory</Button><Button variant="danger-outline" onClick={()=>setConfirm('Open a dispute for this match? Support will review the evidence.')}>Dispute</Button></div></Panel><Panel title="Fair play protection" subtitle="Match result review preview"><div className="notice"><ShieldCheck size={18}/><p>This mock screen previews how evidence review works. No real winnings are held or transferred.</p></div></Panel></div>{confirm&&<ConfirmModal title="Confirm match action" message={confirm} confirmLabel="Continue" onClose={()=>setConfirm('')} onConfirm={()=>{setConfirm('');notify('Your request was submitted for review')}}/>}</>
}

function TransactionRows({rows}) {
  return <div className="transaction-list">{rows.map(transaction=><div className="transaction-row" key={transaction.id}><span className={`transaction-icon ${transaction.amount>0?'credit':''}`}>{transaction.amount>0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</span><div className="row-grow"><strong>{transaction.title}</strong><small>{transaction.date} · {transaction.id}</small></div><strong className={transaction.amount>0?'positive-text':''}>{transaction.amount>0?'+':''}{formatINR(transaction.amount)}</strong><Status>{transaction.status}</Status></div>)}</div>
}

export function WalletPage({notify}) {
  const [filter,setFilter]=useState('All'); const [modal,setModal]=useState(''); const [confirm,setConfirm]=useState('')
  const rows=filter==='All'?transactions:transactions.filter(row=>filter==='Credits'?row.amount>0:row.amount<0)
  return <><PageTitle eyebrow="WALLET & PAYMENTS" title="Your wallet" subtitle="Manage funds securely and review every transaction."/><div className="wallet-hero"><div><small>AVAILABLE BALANCE</small><strong>{formatINR(player.balance)}</strong><span><i/> Wallet protected and ready</span></div><div className="button-row"><Button onClick={()=>setModal('Add money')}><ArrowDownLeft size={16}/> Add money</Button><Button variant="secondary" onClick={()=>setModal('Withdraw')}>Withdraw <ArrowUpRight size={16}/></Button></div></div><Panel title="Transaction history" subtitle="Track deposits, match entries, and winnings" action={<div className="filter-tabs compact">{['All','Credits','Debits'].map(item=><button type="button" aria-pressed={filter===item} className={filter===item?'selected':''} key={item} onClick={()=>setFilter(item)}>{item}</button>)}</div>}>{rows.length?<TransactionRows rows={rows}/>:<EmptyState title="No matching transactions" description="Try a different wallet activity filter."/>}</Panel>{modal&&<MoneyModal mode={modal} onClose={()=>setModal('')} onSubmit={()=>{setConfirm(modal);setModal('')}}/>}{confirm&&<ConfirmModal title={`Confirm ${confirm.toLowerCase()} request`} message={`Your ${confirm.toLowerCase()} request will be submitted for processing. This demo will not move real money.`} confirmLabel="Submit request" onClose={()=>setConfirm('')} onConfirm={()=>{setConfirm('');notify('Wallet request submitted')}}/>}</>
}

function MoneyModal({mode,onClose,onSubmit}) {
  return <Modal title={mode} onClose={onClose}><form className="form-stack" onSubmit={event=>{event.preventDefault();onSubmit()}}><FormField label="Amount (₹)"><input type="number" min="100" max="10000" step="50" defaultValue="500" required/></FormField>{mode==='Add money'?<FormField label="Payment method"><select><option>UPI · aarav@okaxis</option><option>UPI · aarav@okhdfcbank</option></select></FormField>:<FormField label="Withdraw to UPI ID"><input defaultValue="aarav.m@okaxis" required/></FormField>}<p className="form-disclaimer">Mock payment interface · No real transaction will be made.</p><div className="modal-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Continue</Button></div></form></Modal>
}

export function SupportPage({notify}) {
  const [modal,setModal]=useState(false); const [items,setItems]=useState(tickets); const [selected,setSelected]=useState(null)
  return <><PageTitle eyebrow="PLAYER CARE" title="Support" subtitle="We’re here to help with your account, matches, and payments." action={<Button onClick={()=>setModal(true)}><Plus size={16}/> Create ticket</Button>}/><div className="support-banner"><span><Headphones size={20}/></span><div><strong>Need a quick answer?</strong><p>Our player care team usually replies within 15 minutes.</p></div><span className="online-label"><i/> Online now</span></div><Panel title="Your tickets" subtitle="Follow the progress of your support requests">{items.length?<div className="ticket-list">{items.map(ticket=><article className="ticket-row" key={ticket.id}><span className="ticket-icon"><Headphones size={17}/></span><div className="row-grow"><strong>{ticket.subject}</strong><small>{ticket.id} · {ticket.category} · {ticket.date}</small></div><Status>{ticket.status}</Status><button className="text-link" onClick={()=>setSelected(ticket)}>View ticket →</button></article>)}</div>:<EmptyState title="No support tickets" description="Create a ticket and our player care team will follow up." action={<Button variant="secondary" onClick={()=>setModal(true)}>Create ticket</Button>}/>}</Panel>{modal&&<Modal title="Create a support ticket" onClose={()=>setModal(false)}><form className="form-stack" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);const ticket={id:`TK-${Date.now().toString().slice(-4)}`,subject:data.get('subject'),category:data.get('category'),details:data.get('details'),date:'Just now',status:'Open'};setItems([ticket,...items]);setModal(false);notify('Support ticket created') }}><FormField label="Topic"><select name="category"><option>Match issue</option><option>Payments</option><option>Account</option><option>Other</option></select></FormField><FormField label="Subject"><input name="subject" placeholder="Briefly describe the issue" required/></FormField><FormField label="Details"><textarea name="details" rows="4" placeholder="Include any details that could help us" required/></FormField><div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setModal(false)}>Cancel</Button><Button type="submit">Submit ticket</Button></div></form></Modal>}{selected&&<Modal title={`Ticket ${selected.id}`} onClose={()=>setSelected(null)}><div className="ticket-detail"><Status>{selected.status}</Status><h3>{selected.subject}</h3><p>{selected.details||'Our player care team has received your request and is reviewing it.'}</p><small>{selected.category} · {selected.date}</small></div><div className="modal-actions"><Button variant="secondary" onClick={()=>setSelected(null)}>Close</Button></div></Modal>}</>
}

export function AuthPage({mode,onSuccess}) {
  const navigate=useNavigate(); const signup=mode==='signup'; const forgot=mode==='forgot-password'; const [sent,setSent]=useState(false)
  const title=signup?'Create your account':forgot?'Reset your passcode':'Welcome back'
  function submit(event){
    event.preventDefault()
    if(signup){const values=new FormData(event.currentTarget);if(values.get('passcode')!==values.get('confirmPasscode')){event.currentTarget.elements.confirmPasscode.setCustomValidity('Passcodes do not match.');event.currentTarget.elements.confirmPasscode.reportValidity();return}}
    if(forgot){setSent(true);onSuccess?.('Passcode reset instructions are ready for your phone.');return}
    onSuccess?.(signup?'Your demo account is ready.':'Signed in to your demo account.');navigate('/dashboard')
  }
  return <div className="auth-layout"><Link to="/login" className="brand"><span className="brand-mark">✦</span><span>play<span>nexa</span></span></Link><div className="auth-card"><div className="eyebrow">PLAY NEXA · SKILL GAMING</div><h1>{title}</h1><p>{forgot?'We’ll help you securely get back into your account.':signup?'Join the community and put your skills to the test.':'Sign in securely with your registered phone number.'}</p>{sent?<div className="notice"><ShieldCheck size={18}/><p>Reset instructions are ready for the phone number you entered. This is a mock flow.</p></div>:<form className="form-stack" onSubmit={submit}>{signup&&<FormField label="Full name"><input name="fullName" placeholder="e.g. Aarav Mehta" required/></FormField>}<FormField label="Phone number"><div className="phone-input"><span>🇮🇳 +91</span><input name="phone" type="tel" inputMode="numeric" pattern="[0-9]{10}" placeholder="98765 43210" required/></div></FormField>{signup&&<><FormField label="Email address"><input name="email" type="email" placeholder="you@example.com" required/></FormField><div className="form-grid"><FormField label="Date of birth"><input name="dob" type="date" required/></FormField><FormField label="Gender"><select name="gender" defaultValue=""><option value="" disabled>Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></FormField></div><FormField label="UPI ID"><input name="upi" placeholder="name@bank" required/></FormField></>}{!forgot&&<FormField label="6-digit passcode"><input name="passcode" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" placeholder="••••••" required/></FormField>}{signup&&<FormField label="Confirm passcode"><input name="confirmPasscode" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" placeholder="••••••" required onInput={event=>event.currentTarget.setCustomValidity('')}/></FormField>}<Button type="submit" className="auth-submit">{forgot?'Send reset instructions':signup?'Create account':'Sign in'} →</Button></form>}{!signup&&!forgot&&<Link className="auth-help" to="/forgot-password">Forgot passcode?</Link>}{!forgot&&<div className="auth-switch">{signup?'Already have an account?':'New to Play Nexa?'} <Link to={signup?'/login':'/signup'}>{signup?'Sign in':'Create account'}</Link></div>}{forgot&&!sent&&<div className="auth-switch"><Link to="/login">← Back to sign in</Link></div>}<small className="auth-safe"><ShieldCheck size={14}/> Demo authentication · No real account is created.</small></div><span className="auth-footer">© 2026 Play Nexa · Play fair. Play smart.</span></div>
}
